version: '3'
services:
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - '80:5000'
    environment:
      MONGO_DB_URI: 'mongodb://mongo:27017/todo'
      JWT_KEY: 'secret-key'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
